"""Generate a config of the shock transfer model with many spot markets.

This is the counterpart of config.json.sh of the Parallel sample of Plham. For
example, config-009.json of this sample is generated by::

    python -m samples.parallel_main.make_config 9 -o samples/parallel_main/config-009.json

Without ``-o``, the config is written to the standard output. See ``--help`` for the
other options.
"""

import argparse
import json
import sys
from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Sequence


def make_config(
    n_spots: int,
    steps: int = 500,
    agents_per_market: int = 500,
    arbitrage_agents: int = 100,
    order_rate: float = 0.1,
    with_workload: bool = True,
    bs_num_samples: int = 10,
    bs_num_steps: int = 10,
    with_shock: bool = True,
    num_parallel: Optional[int] = None,
) -> Dict[str, Any]:
    """Make a config of the shock transfer model with spot markets and an index market.

    Args:
        n_spots (int): number of spot markets.
        steps (int): number of steps of the session.
        agents_per_market (int): number of FCN agents for each market.
        arbitrage_agents (int): number of arbitrage agents.
        order_rate (float): probability that an FCN agent submits orders.
        with_workload (bool): whether the FCN agents process the workload.
        bs_num_samples (int): number of paths of the workload.
        bs_num_steps (int): number of time steps of each path of the workload.
        with_shock (bool): whether the fundamental price shock is enabled.
        num_parallel (int, Optional): number of parallel workers. If None, it is not
            written in the config.

    Returns:
        Dict[str, Any]: config.

    """
    if n_spots < 1:
        raise ValueError("n_spots have to be positive")
    spots: List[str] = [f"SpotMarket-{i}" for i in range(1, n_spots + 1)]
    simulation: Dict[str, Any] = {
        "markets": spots + ["IndexMarket-I"],
        "agents": [f"FCNAgents-{i}" for i in range(1, n_spots + 1)]
        + ["FCNAgents-I", "ArbitrageAgents"],
        "sessions": [
            {
                "sessionName": 1,
                "iterationSteps": steps,
                "withOrderPlacement": True,
                "withOrderExecution": True,
                "withPrint": True,
                "maxNormalOrders": 10000000000,
                "maxHighFrequencyOrders": 1,
                "events": ["FundamentalPriceShock"],
            }
        ],
    }
    if num_parallel is not None:
        simulation["numParallel"] = num_parallel
    config: Dict[str, Any] = {
        "simulation": simulation,
        "FundamentalPriceShock": {
            "class": "FundamentalPriceShock",
            "target": "SpotMarket-1",
            "triggerTime": 0,
            "priceChangeRate": -0.1,
            "enabled": with_shock,
        },
        "SpotMarket": {
            "class": "Market",
            "tickSize": 0.00001,
            "marketPrice": 300.0,
            "outstandingShares": 25000,
        },
    }
    for spot in spots:
        config[spot] = {"extends": "SpotMarket"}
    config["IndexMarket-I"] = {
        "class": "IndexMarket",
        "tickSize": 0.00001,
        "marketPrice": 300.0,
        "outstandingShares": 25000,
        "markets": spots,
    }
    config["FCNAgent"] = {
        "class": "WorkloadFCNAgent",
        "numAgents": agents_per_market,
        "markets": ["Market"],
        "assetVolume": 50,
        "cashAmount": 10000,
        "fundamentalWeight": {"expon": [1.0]},
        "chartWeight": {"expon": [0.0]},
        "noiseWeight": {"expon": [1.0]},
        "noiseScale": 0.001,
        "timeWindowSize": [100, 200],
        "orderMargin": [0.0, 0.1],
        "orderRate": order_rate,
        "bsWorkload": with_workload,
        "bsNumSamples": bs_num_samples,
        "bsNumSteps": bs_num_steps,
    }
    for i, spot in enumerate(spots, start=1):
        config[f"FCNAgents-{i}"] = {"extends": "FCNAgent", "markets": [spot]}
    config["FCNAgents-I"] = {
        "extends": "FCNAgent",
        "markets": ["IndexMarket-I"],
        "fundamentalWeight": {"expon": [0.5]},
    }
    config["ArbitrageAgents"] = {
        "class": "ArbitrageAgent",
        "numAgents": arbitrage_agents,
        "markets": ["IndexMarket-I"] + spots,
        "assetVolume": 50,
        "cashAmount": 150000,
        "orderVolume": 1,
        "orderThresholdPrice": 1.0,
    }
    return config


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = argparse.ArgumentParser(
        description="Generate a config of the shock transfer model with spot markets."
    )
    parser.add_argument("spots", type=int, help="number of spot markets")
    parser.add_argument(
        "--steps",
        type=int,
        default=500,
        help="number of steps of the session (default: 500)",
    )
    parser.add_argument(
        "--agents-per-market",
        type=int,
        default=500,
        help="number of FCN agents for each market (default: 500)",
    )
    parser.add_argument(
        "--arbitrage-agents",
        type=int,
        default=100,
        help="number of arbitrage agents (default: 100)",
    )
    parser.add_argument(
        "--order-rate",
        type=float,
        default=0.1,
        help="probability that an FCN agent submits orders (default: 0.1)",
    )
    parser.add_argument(
        "--no-workload", action="store_true", help="disable the workload"
    )
    parser.add_argument(
        "--bs-num-samples",
        type=int,
        default=10,
        help="number of paths of the workload (default: 10)",
    )
    parser.add_argument(
        "--bs-num-steps",
        type=int,
        default=10,
        help="number of time steps of each path of the workload (default: 10)",
    )
    parser.add_argument(
        "--no-shock", action="store_true", help="disable the fundamental price shock"
    )
    parser.add_argument(
        "--num-parallel",
        type=int,
        default=None,
        help="number of parallel workers written in the config; "
        "not written if not given",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default=None,
        help="output file; the standard output if not given",
    )
    args = parser.parse_args(argv)
    config: Dict[str, Any] = make_config(
        n_spots=args.spots,
        steps=args.steps,
        agents_per_market=args.agents_per_market,
        arbitrage_agents=args.arbitrage_agents,
        order_rate=args.order_rate,
        with_workload=not args.no_workload,
        bs_num_samples=args.bs_num_samples,
        bs_num_steps=args.bs_num_steps,
        with_shock=not args.no_shock,
        num_parallel=args.num_parallel,
    )
    if args.output is None:
        json.dump(config, sys.stdout, indent=4)
        sys.stdout.write("\n")
    else:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            json.dump(config, f, indent=4)
            f.write("\n")


if __name__ == "__main__":
    main()
